## concatenation

In [1]:
import pandas as pd

In [4]:
df1 = pd.DataFrame({
    "id" : [1,2,3,4] , 
    "name": ["Rahul" , "Diplip" , "Jayant" ,"Dev" ]
})

df2 = pd.DataFrame({
    "id" : [5,6,7] , 
    "name": ["Neha" , "Aditi" , "Alex" ]
})

In [5]:
df1

   id    name
0   1   Rahul
1   2  Diplip
2   3  Jayant
3   4     Dev

In [6]:
df2

   id   name
0   5   Neha
1   6  Aditi
2   7   Alex

In [7]:
pd.concat([df1 , df2])  #row wise

   id    name
0   1   Rahul
1   2  Diplip
2   3  Jayant
3   4     Dev
0   5    Neha
1   6   Aditi
2   7    Alex

In [8]:
pd.concat([df2 , df1] , ignore_index=True)  #row wise

   id    name
0   5    Neha
1   6   Aditi
2   7    Alex
3   1   Rahul
4   2  Diplip
5   3  Jayant
6   4     Dev

In [9]:
pd.concat([df1 , df2] , axis = 1)  #col wise

   id    name   id   name
0   1   Rahul  5.0   Neha
1   2  Diplip  6.0  Aditi
2   3  Jayant  7.0   Alex
3   4     Dev  NaN    NaN